source 'http://rubygems.org'

# TODO: Read .ruby-version

gem 'sinatra'
gem 'activerecord', require: 'active_record'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'bcrypt'
# TODO: gem 'tux'
gem 'puma'
gem 'rackup'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner'
end
