inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'blue-eyes.gemspec' # IGNORE: Rubocop doesn't recognize our version is within range.

Metrics/ClassLength:
  Exclude:
    - 'lib/blue_eyes/generators/app/app_generator.rb' # IGNORE: Number of methods to generate app exceeds limit

Style/Documentation:
  Exclude:
    - 'test/**/*'
