# remaining linting tasks

# Ignore (aka Exclude) offenses in generated app folder
# NOTE: Include whenever linting while coding
AllCops:
  Exclude:
    - 'app/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/blue_eyes/generators/model/model_generator.rb' # TODO: Fix setup method

Naming/PredicateMethod:
  Exclude:
    - 'lib/blue_eyes/cli.rb' # Can't fix. Required by Thor
