# frozen_string_literal: true

# Module to provide helper methods for running generators in specs
module GeneratorHelpers
  require 'thor'
  require 'fileutils'

  # Runs a Thor generator inside a temporary directory.
  #
  # Example:
  #   run_generator BlueEyes::Generators::ModelGenerator, ["post"]
  #
  def run_generator(generator_class, args = [], behavior: :invoke)
    prepare_generator_destination

    generator = generator_class.new([], args, destination_root: generator_destination)
    allow(generator).to receive(:behavior).and_return(behavior)

    capture_io { generator.invoke_all }
    generator
  end

  # Path to the temporary generator output directory
  def generator_destination
    @generator_destination ||= File.expand_path('../../tmp/generator', __dir__)
  end

  # Ensures the generator output directory is clean before each run
  def prepare_generator_destination
    FileUtils.rm_rf(generator_destination)
    FileUtils.mkdir_p(generator_destination)
  end

  # Reads a file generated by a generator
  def generated_file(path)
    File.read(File.join(generator_destination, path))
  end

  # Checks whether a file exists in the generator output
  def generated_file_exists?(path)
    File.exist?(File.join(generator_destination, path))
  end
end
